version: '3.8'

services:
  antink-server:
    build: .
    container_name: antink-server
    privileged: true
    volumes:
      - ./it24_host:/it24_host
      - ./antink_mount:/antink_mount:rshared  # Perhatikan :rshared di sini
      - ./antink-logs:/var/log
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    restart: unless-stopped

  antink-logger:
    image: alpine:latest
    container_name: antink-logger
    volumes:
      - ./antink-logs:/var/log
    depends_on:
      antink-server:
        condition: service_healthy
    restart: unless-stopped
